web:
  container_name: jira-mgwallet.hipay-pos-platform.com
  image: hipay/magento_wallet:walmag-10
  ports:
    - "80"
  links:
    - mysql
  env_file:
    - env
mysql:
  image: mysql:5.6.23
  env_file:
    - env